config { 
        type: "view",
        description: 'SQL to get all individuals cars data to create a report'
       }

WITH base AS (
  SELECT
    *,
    EXTRACT(YEAR FROM DATE(PIRM_REG_DATA)) AS registration_year,
    EXTRACT(YEAR FROM CURRENT_DATE()) AS current_year
  FROM `vl-data-learn.lithuania_statistics.Atviri_TP_parko_duomenys`
  WHERE VALD_TIPAS = 'Fizinis'
)

SELECT
  *,
  (current_year - registration_year) AS car_age_up_to_current_year
FROM base

